### ISSUE TITLE
License statement

### ISSUE THREAD

**Issue by fabaff** [jeeftor/weatherflow4py#24]
Currently there is no license statement. Could you please add a `LICENSE` file that contains the license text.

In the current state it's problematic, especially for the Home Assistant integration, as one could consider this module as non-free.

Thanks.

**Comment by jeeftor** [comment]
I assume no license meant open as can be. Which should I use? MIT? Is that the good one

**Comment by fabaff** [comment]
All [OSI approved open source license](https://opensource.org/licenses) are a good choice. MIT is simple and straight-forward and was used by Home Assistant till 0.37.

**Comment by jeeftor** [comment]
https://github.com/jeeftor/weatherflow4py/blob/master/LICENSE

Wer're good! thanks
